name: Setup Rclone action.
description: Setup/Install Rclone for GitHub Actions
branding:
  icon: cloud
  color: blue
inputs:
  rclone_config:
    description: Rclone config file encoded in base64
    default: false
    
runs:
  using: composite
  steps:
    - name: Download Rclone for Linux
      if: runner.os == 'Linux'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/Linux.sh
      
    - name: Download Rclone for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: '& $env:GITHUB_ACTION_PATH\scripts\download\Windows.ps1'
      
    - name: Download Rclone for macOS
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/macOS.sh
      
    - name: Install Rclone on tool cache
      uses: beqjanus/tool-cache@main
      with:
        folder_name: Rclone
        
    - name: Sign in to Rclone using Rclone config on Unix-like
      if: (runner.os == 'Linux' || runner.os == 'macOS') && inputs.rclone_config != 'false'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/sign-in/Unix-like.sh
      env:
        rclone_config: ${{ inputs.rclone_config }}
        
    - name: Sign in to Rclone using Rclone config on Windows
      if: runner.os == 'Windows' && inputs.rclone_config != 'false'
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH\scripts\sign-in\Windows.ps1'
      env:
        rclone_config: ${{ inputs.rclone_config }}